version: '3'
services:
  # O Banco de Dados de Destino (DW)
  postgres_dw:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
    ports:
      - "5433:5432" # Porta externa 5433 para não conflitar se tiver outro postgres

  # O Airflow (Versão simplificada para estudo)
  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_dw/airflow_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: standalone
    depends_on:
      - postgres_dw